# Generated by Django 3.1.1 on 2020-11-17 02:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEventLog',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_name', models.CharField(db_index=True, max_length=50, null=True)),
                ('account_number', models.PositiveIntegerField(db_index=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999999)])),
                ('account_description', models.TextField(blank=True)),
                ('account_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1)),
                ('account_catagory', models.IntegerField(choices=[(1, 'Assest'), (2, 'Liability'), (3, 'Equity'), (4, 'Revenue'), (5, 'Expense')], null=True)),
                ('account_subcatagory', models.IntegerField(choices=[(1, 'Checking'), (2, 'Petty cash'), (3, 'Inventory'), (4, 'Accounts receivable'), (5, 'Payroll tax liabilities'), (6, 'Sales tax collected'), (7, 'Credit memo liability'), (8, 'Accounts payable'), (9, 'Owner’s equity'), (10, 'Common stock'), (11, 'Retained earnings'), (12, 'Product sales'), (13, 'Earned interest'), (14, 'Miscellaneous income'), (15, 'Payroll'), (16, 'Insurance'), (17, 'Rent'), (18, 'Equipment'), (19, 'Cost of goods sold(COGS)')], null=True)),
                ('account_inital_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_creation_date', models.DateTimeField(blank=True, editable=False)),
                ('account_modified_date', models.DateTimeField(blank=True, editable=False)),
                ('account_modified_user', models.IntegerField(blank=True, null=True)),
                ('account_statement', models.IntegerField(choices=[(1, 'Income Sheet'), (2, 'Balance Sheet'), (3, 'Retained Earnings')], null=True)),
                ('account_status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('P', 'Pending')], default='A', max_length=1)),
                ('account_comment', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'db_table': 'accounting_eventlog',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
