# Generated by Django 3.1.1 on 2020-11-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20201117_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='journal_account_names',
            new_name='journal_account_name_credits',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='journal_account_numbers',
            new_name='journal_account_name_debits',
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_account_number_credits',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_account_number_debits',
            field=models.JSONField(null=True),
        ),
    ]
