# Generated by Django 3.1.3 on 2020-11-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('password_expiration', models.IntegerField(default=0)),
                ('user_type', models.IntegerField(choices=[(1, 'Accountant'), (2, 'Manager'), (3, 'Admin')], default=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('security_question', models.IntegerField(choices=[(1, 'Whats is your mother maiden name?'), (2, 'What is your favorite color?'), (3, 'What is your biggest fear?')], null=True)),
                ('security_answer', models.CharField(max_length=100, null=True)),
                ('deactive_time_start', models.DateField(blank=True, null=True)),
                ('deactive_time_end', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
