# Generated by Django 3.1.3 on 2020-11-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_name', models.CharField(db_index=True, max_length=50, null=True)),
                ('account_number', models.PositiveIntegerField(db_index=True, null=True)),
                ('account_description', models.TextField(blank=True)),
                ('account_side', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=10)),
                ('account_catagory', models.CharField(choices=[('Assests', 'Assests'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Revenues', 'Revenues'), ('Expenses', 'Expenses')], max_length=255, null=True)),
                ('account_subcatagory', models.CharField(choices=[('Cash', 'Cash'), ('Receivables', 'Receivables'), ('Inventories', 'Inventories'), ('Prepaid Items', 'Prepaid Items'), ('Long-Term Investments', 'Long-Term Investments'), ('Land', 'Land'), ('Building', 'Building'), ('Equipment', 'Equipment'), ('Intangibles', 'Intangibles'), ('Short-Term Payables', 'Short-Term Payables'), ('Employee Payroll', 'Employee Payroll'), ('Sales Tax', 'Sales Tax'), ('Deferred Revenues and Long-Term Debt', 'Deferred Revenues and Long-Term Debt'), ('Long-Term Liabilities', 'Long-Term Liabilities'), ('Operating Revenues', 'Operating Revenues'), ('Other Revenues', 'Other Revenues'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Selling Expenses', 'Selling Expenses'), ('General and Administrative Expenses', 'General and Administrative Expenses'), ('Othe Expenses', 'Othe Expenses')], max_length=255, null=True)),
                ('account_inital_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_creation_date', models.DateTimeField(blank=True, editable=False)),
                ('account_statement', models.CharField(choices=[('Income', 'Income'), ('Balance', 'Balance'), ('Retained', 'Retained')], max_length=50, null=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('account_comment', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'db_table': 'accounting_eventlog',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50, null=True, unique=True)),
                ('account_number', models.PositiveIntegerField(null=True, unique=True)),
                ('account_description', models.TextField(blank=True)),
                ('account_side', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=10)),
                ('account_catagory', models.CharField(choices=[('Assests', 'Assests'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Revenues', 'Revenues'), ('Expenses', 'Expenses')], max_length=255, null=True)),
                ('account_subcatagory', models.CharField(choices=[('Cash', 'Cash'), ('Receivables', 'Receivables'), ('Inventories', 'Inventories'), ('Prepaid Items', 'Prepaid Items'), ('Long-Term Investments', 'Long-Term Investments'), ('Land', 'Land'), ('Building', 'Building'), ('Equipment', 'Equipment'), ('Intangibles', 'Intangibles'), ('Short-Term Payables', 'Short-Term Payables'), ('Employee Payroll', 'Employee Payroll'), ('Sales Tax', 'Sales Tax'), ('Deferred Revenues and Long-Term Debt', 'Deferred Revenues and Long-Term Debt'), ('Long-Term Liabilities', 'Long-Term Liabilities'), ('Operating Revenues', 'Operating Revenues'), ('Other Revenues', 'Other Revenues'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Selling Expenses', 'Selling Expenses'), ('General and Administrative Expenses', 'General and Administrative Expenses'), ('Othe Expenses', 'Othe Expenses')], max_length=255, null=True)),
                ('account_inital_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_creation_date', models.DateTimeField(auto_now_add=True)),
                ('account_statement', models.CharField(choices=[('Income', 'Income'), ('Balance', 'Balance'), ('Retained', 'Retained')], max_length=50, null=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('account_comment', models.TextField(blank=True)),
                ('account_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_creation_date',),
            },
        ),
    ]
