# Generated by Django 3.1.3 on 2020-11-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_ledger_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
