# Generated by Django 3.1.3 on 2020-11-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20201127_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='ledger_amount',
            new_name='ledger_credit',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='ledger_type',
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
