# Generated by Django 3.1.3 on 2020-12-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20201128_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='ledger_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
