# Generated by Django 3.1.3 on 2020-12-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20201203_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-account_creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-transaction_date',)},
        ),
    ]
