# Generated by Django 3.1.3 on 2020-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20201203_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/transaction_documents/'),
        ),
    ]
