# Generated by Django 3.1.3 on 2020-12-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_transaction_transaction_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_document',
            field=models.FileField(blank=True, null=True, upload_to='transaction_documents/'),
        ),
    ]
